--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["ZAP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of ZAP, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["ZAP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["ZAP"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		SnapshotBuildings = table.freeze({
			SetCallback = noop
		}),
		PlayersCreateBuilding = table.freeze({
			On = noop
		}),
		PlayerRequestPalceBulidings = table.freeze({
			Fire = noop
		}),
		PlayerDataUpdate = table.freeze({
			On = noop
		}),
		PlayerClickCollector = table.freeze({
			Fire = noop
		}),
		LoadSnapshot = table.freeze({
			SetCallback = noop
		}),
		ClientReady = table.freeze({
			Fire = noop
		}),
		AssingZoneOwner = table.freeze({
			SetCallback = noop
		}),
	}) :: Events
end
local remotes = ReplicatedStorage:WaitForChild("ZAP")

local reliable = remotes:WaitForChild("ZAP_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected ZAP_RELIABLE to be a RemoteEvent")

export type BuildingEntry = ({
	["SnapToString"]: (string),
	["BuildingTypeEnum"]: (number),
	["BuildingLevel"]: (number),
	["EndTime"]: (number),
	["LastCollectedTime"]: (number),
})
export type DataKey = ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience")
export type CollectorData = ({
	["Timestamp"]: (number),
	["ProductionRate"]: (number),
	["Capacity"]: (number),
})
export type Collector = ({
	["GoldCollector"]: ({
		["Timestamp"]: (number),
		["ProductionRate"]: (number),
		["Capacity"]: (number),
	}),
	["ElixirCollector"]: ({
		["Timestamp"]: (number),
		["ProductionRate"]: (number),
		["Capacity"]: (number),
	}),
})

local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(5)
local reliable_event_queue: { [number]: { any } } = table.create(5)
reliable_event_queue[1] = {}
reliable_events[2] = {}
reliable_event_queue[2] = {}
reliable_events[4] = {}
reliable_event_queue[4] = {}
reliable_event_queue[0] = {}
reliable_event_queue[3] = {}
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 1 then -- SnapshotBuildings
			local value
			value = {  }
			local len_1 = buffer.readu16(incoming_buff, read(2))
			value["FolderName"] = buffer.readstring(incoming_buff, read(len_1), len_1)
			assert(utf8.len(value["FolderName"]) ~= nil, "value is not valid utf-8")
			local len_2 = buffer.readu16(incoming_buff, read(2))
			value["Buildings"] = table.create(len_2)
			for i_1 = 1, len_2 do
				local val_1
				val_1 = {  }
				local len_3 = buffer.readu16(incoming_buff, read(2))
				val_1["SnapToString"] = buffer.readstring(incoming_buff, read(len_3), len_3)
				assert(utf8.len(val_1["SnapToString"]) ~= nil, "value is not valid utf-8")
				val_1["BuildingTypeEnum"] = buffer.readu8(incoming_buff, read(1))
				val_1["BuildingLevel"] = buffer.readu8(incoming_buff, read(1))
				val_1["EndTime"] = buffer.readu32(incoming_buff, read(4))
				val_1["LastCollectedTime"] = buffer.readu32(incoming_buff, read(4))
				value["Buildings"][i_1] = val_1
			end
			if reliable_events[1] then
				task.spawn(reliable_events[1], value)
			else
				table.insert(reliable_event_queue[1], value)
				if #reliable_event_queue[1] > 64 then
					warn(`[ZAP] {#reliable_event_queue[1]} events in queue for SnapshotBuildings. Did you forget to attach a listener?`)
				end
			end
		elseif id == 2 then -- PlayersCreateBuilding
			local value
			value = {  }
			value["BuildingTypeEnum"] = buffer.readu8(incoming_buff, read(1))
			value["Position"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			if reliable_events[2][1] then
				for _, cb in reliable_events[2] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[2], value)
				if #reliable_event_queue[2] > 64 then
					warn(`[ZAP] {#reliable_event_queue[2]} events in queue for PlayersCreateBuilding. Did you forget to attach a listener?`)
				end
			end
		elseif id == 4 then -- PlayerDataUpdate
			local value
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			if bit32.btest(bool_1, 0b0000000000000001) then
				value["Key"] = "Golds"
			elseif bit32.btest(bool_1, 0b0000000000000010) then
				value["Key"] = "Elixirs"
			elseif bit32.btest(bool_1, 0b0000000000000100) then
				value["Key"] = "Gems"
			elseif bit32.btest(bool_1, 0b0000000000001000) then
				value["Key"] = "Level"
			elseif bit32.btest(bool_1, 0b0000000000010000) then
				value["Key"] = "Experience"
			end
			if bit32.btest(bool_1, 0b0000000000100000) then
				incoming_ipos = incoming_ipos + 1
				value["Value"] = incoming_inst[incoming_ipos]
			else
				value["Value"] = nil
			end
			if reliable_events[4][1] then
				for _, cb in reliable_events[4] do
					task.spawn(cb, value)
				end
			else
				table.insert(reliable_event_queue[4], value)
				if #reliable_event_queue[4] > 64 then
					warn(`[ZAP] {#reliable_event_queue[4]} events in queue for PlayerDataUpdate. Did you forget to attach a listener?`)
				end
			end
		elseif id == 0 then -- LoadSnapshot
			local value
			value = {  }
			value["Golds"] = buffer.readu32(incoming_buff, read(4))
			value["Elixirs"] = buffer.readu32(incoming_buff, read(4))
			value["Gems"] = buffer.readu32(incoming_buff, read(4))
			value["Level"] = buffer.readu32(incoming_buff, read(4))
			value["Experience"] = buffer.readu32(incoming_buff, read(4))
			local len_4 = buffer.readu16(incoming_buff, read(2))
			value["Buildings"] = table.create(len_4)
			for i_2 = 1, len_4 do
				local val_2
				val_2 = {  }
				local len_5 = buffer.readu16(incoming_buff, read(2))
				val_2["SnapToString"] = buffer.readstring(incoming_buff, read(len_5), len_5)
				assert(utf8.len(val_2["SnapToString"]) ~= nil, "value is not valid utf-8")
				val_2["BuildingTypeEnum"] = buffer.readu8(incoming_buff, read(1))
				val_2["BuildingLevel"] = buffer.readu8(incoming_buff, read(1))
				val_2["EndTime"] = buffer.readu32(incoming_buff, read(4))
				val_2["LastCollectedTime"] = buffer.readu32(incoming_buff, read(4))
				value["Buildings"][i_2] = val_2
			end
			value["Collectors"] = {  }
			value["Collectors"]["GoldCollector"] = {  }
			value["Collectors"]["GoldCollector"]["Timestamp"] = buffer.readu32(incoming_buff, read(4))
			value["Collectors"]["GoldCollector"]["ProductionRate"] = buffer.readu32(incoming_buff, read(4))
			value["Collectors"]["GoldCollector"]["Capacity"] = buffer.readu32(incoming_buff, read(4))
			value["Collectors"]["ElixirCollector"] = {  }
			value["Collectors"]["ElixirCollector"]["Timestamp"] = buffer.readu32(incoming_buff, read(4))
			value["Collectors"]["ElixirCollector"]["ProductionRate"] = buffer.readu32(incoming_buff, read(4))
			value["Collectors"]["ElixirCollector"]["Capacity"] = buffer.readu32(incoming_buff, read(4))
			if reliable_events[0] then
				task.spawn(reliable_events[0], value)
			else
				table.insert(reliable_event_queue[0], value)
				if #reliable_event_queue[0] > 64 then
					warn(`[ZAP] {#reliable_event_queue[0]} events in queue for LoadSnapshot. Did you forget to attach a listener?`)
				end
			end
		elseif id == 3 then -- AssingZoneOwner
			local value
			value = {  }
			local len_6 = buffer.readu16(incoming_buff, read(2))
			value["FolderName"] = buffer.readstring(incoming_buff, read(len_6), len_6)
			assert(utf8.len(value["FolderName"]) ~= nil, "value is not valid utf-8")
			if reliable_events[3] then
				task.spawn(reliable_events[3], value)
			else
				table.insert(reliable_event_queue[3], value)
				if #reliable_event_queue[3] > 64 then
					warn(`[ZAP] {#reliable_event_queue[3]} events in queue for AssingZoneOwner. Did you forget to attach a listener?`)
				end
			end
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	SnapshotBuildings = {
		SetCallback = function(Callback: (Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		})) -> ()): () -> ()
			reliable_events[1] = Callback
			for _, value in reliable_event_queue[1] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[1] = {}
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	PlayersCreateBuilding = {
		On = function(Callback: (Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		})) -> ())
			table.insert(reliable_events[2], Callback)
			for _, value in reliable_event_queue[2] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[2] = {}
			return function()
				table.remove(reliable_events[2], table.find(reliable_events[2], Callback))
			end
		end,
	},
	PlayerRequestPalceBulidings = {
		Fire = function(Value: ({
			["SnapToString"]: (string),
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_7 = #Value["SnapToString"]
			assert(utf8.len(Value["SnapToString"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_7)
			alloc(len_7)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["SnapToString"], len_7)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
		end,
	},
	PlayerDataUpdate = {
		On = function(Callback: (Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		})) -> ())
			table.insert(reliable_events[4], Callback)
			for _, value in reliable_event_queue[4] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[4] = {}
			return function()
				table.remove(reliable_events[4], table.find(reliable_events[4], Callback))
			end
		end,
	},
	PlayerClickCollector = {
		Fire = function(Value: ({
			["CollectorType"]: (string),
		}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			local len_8 = #Value["CollectorType"]
			assert(utf8.len(Value["CollectorType"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_8)
			alloc(len_8)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["CollectorType"], len_8)
		end,
	},
	LoadSnapshot = {
		SetCallback = function(Callback: (Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		})) -> ()): () -> ()
			reliable_events[0] = Callback
			for _, value in reliable_event_queue[0] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[0] = {}
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	ClientReady = {
		Fire = function()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
		end,
	},
	AssingZoneOwner = {
		SetCallback = function(Callback: (Value: ({
			["FolderName"]: (string),
		})) -> ()): () -> ()
			reliable_events[3] = Callback
			for _, value in reliable_event_queue[3] do
				task.spawn(Callback, value)
			end
			reliable_event_queue[3] = {}
			return function()
				reliable_events[3] = nil
			end
		end,
	},
}
type Events = typeof(returns)
return returns
