--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Server generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

if RunService:IsClient() then
	error("Cannot use the server module on the client!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["ZAP"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of ZAP, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["ZAP"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["ZAP"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		SnapshotBuildings = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		PlayersCreateBuilding = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		PlayerRequestPalceBulidings = table.freeze({
			SetCallback = noop
		}),
		PlayerDataUpdate = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		PlayerClickCollector = table.freeze({
			SetCallback = noop
		}),
		LoadSnapshot = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		ClientReady = table.freeze({
			SetCallback = noop
		}),
		AssingZoneOwner = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
	}) :: Events
end

local remotes = ReplicatedStorage:FindFirstChild("ZAP")
if remotes == nil then
	remotes = Instance.new("Folder")
	remotes.Name = "ZAP"
	remotes.Parent = ReplicatedStorage
end

local reliable = remotes:FindFirstChild("ZAP_RELIABLE")
if reliable == nil then
	reliable = Instance.new("RemoteEvent")
	reliable.Name = "ZAP_RELIABLE"
	reliable.Parent = remotes
end

local player_map = {}

local function load_player(player: Player)
	if player_map[player] then
		load(player_map[player])
	else
		load_empty()
	end
end

Players.PlayerRemoving:Connect(function(player)
	player_map[player] = nil
end)
export type BuildingEntry = ({
	["SnapToString"]: (string),
	["BuildingTypeEnum"]: (number),
	["BuildingLevel"]: (number),
	["EndTime"]: (number),
	["LastCollectedTime"]: (number),
})
export type DataKey = ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience")
export type CollectorData = ({
	["Timestamp"]: (number),
	["ProductionRate"]: (number),
	["Capacity"]: (number),
})
export type Collector = ({
	["GoldCollector"]: ({
		["Timestamp"]: (number),
		["ProductionRate"]: (number),
		["Capacity"]: (number),
	}),
	["ElixirCollector"]: ({
		["Timestamp"]: (number),
		["ProductionRate"]: (number),
		["Capacity"]: (number),
	}),
})

local function SendEvents()
	for player, outgoing in player_map do
		if outgoing.used > 0 then
			local buff = buffer.create(outgoing.used)
			buffer.copy(buff, 0, outgoing.buff, 0, outgoing.used)

			reliable:FireClient(player, buff, outgoing.inst)

			outgoing.buff = buffer.create(64)
			outgoing.used = 0
			outgoing.size = 64
			table.clear(outgoing.inst)
		end
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(3)
reliable.OnServerEvent:Connect(function(player, buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- PlayerRequestPalceBulidings
			local value
			value = {  }
			local len_1 = buffer.readu16(incoming_buff, read(2))
			value["SnapToString"] = buffer.readstring(incoming_buff, read(len_1), len_1)
			assert(utf8.len(value["SnapToString"]) ~= nil, "value is not valid utf-8")
			value["BuildingTypeEnum"] = buffer.readu8(incoming_buff, read(1))
			value["Position"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
			if reliable_events[0] then
				task.spawn(reliable_events[0], player, value)
			end
		elseif id == 2 then -- PlayerClickCollector
			local value
			value = {  }
			local len_2 = buffer.readu16(incoming_buff, read(2))
			value["CollectorType"] = buffer.readstring(incoming_buff, read(len_2), len_2)
			assert(utf8.len(value["CollectorType"]) ~= nil, "value is not valid utf-8")
			if reliable_events[2] then
				task.spawn(reliable_events[2], player, value)
			end
		elseif id == 1 then -- ClientReady
			local value
			if reliable_events[1] then
				task.spawn(reliable_events[1], player, value)
			end
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	SnapshotBuildings = {
		Fire = function(Player: Player, Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local len_3 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_3)
			alloc(len_3)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_3)
			local len_4 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_4)
			for i_1 = 1, len_4 do
				local val_1 = Value["Buildings"][i_1]
				local len_5 = #val_1["SnapToString"]
				assert(utf8.len(val_1["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_5)
				alloc(len_5)
				buffer.writestring(outgoing_buff, outgoing_apos, val_1["SnapToString"], len_5)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_1["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_1["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_1["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_1["LastCollectedTime"])
			end
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local len_6 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_6)
			alloc(len_6)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_6)
			local len_7 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_7)
			for i_2 = 1, len_7 do
				local val_2 = Value["Buildings"][i_2]
				local len_8 = #val_2["SnapToString"]
				assert(utf8.len(val_2["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_8)
				alloc(len_8)
				buffer.writestring(outgoing_buff, outgoing_apos, val_2["SnapToString"], len_8)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_2["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_2["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_2["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_2["LastCollectedTime"])
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local len_9 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_9)
			alloc(len_9)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_9)
			local len_10 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_10)
			for i_3 = 1, len_10 do
				local val_3 = Value["Buildings"][i_3]
				local len_11 = #val_3["SnapToString"]
				assert(utf8.len(val_3["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_11)
				alloc(len_11)
				buffer.writestring(outgoing_buff, outgoing_apos, val_3["SnapToString"], len_11)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_3["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_3["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_3["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_3["LastCollectedTime"])
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local len_12 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
			alloc(len_12)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_12)
			local len_13 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_13)
			for i_4 = 1, len_13 do
				local val_4 = Value["Buildings"][i_4]
				local len_14 = #val_4["SnapToString"]
				assert(utf8.len(val_4["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_14)
				alloc(len_14)
				buffer.writestring(outgoing_buff, outgoing_apos, val_4["SnapToString"], len_14)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_4["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_4["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_4["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_4["LastCollectedTime"])
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["FolderName"]: (string),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local len_15 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_15)
			alloc(len_15)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_15)
			local len_16 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_16)
			for i_5 = 1, len_16 do
				local val_5 = Value["Buildings"][i_5]
				local len_17 = #val_5["SnapToString"]
				assert(utf8.len(val_5["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_17)
				alloc(len_17)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5["SnapToString"], len_17)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_5["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_5["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_5["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_5["LastCollectedTime"])
			end
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	PlayersCreateBuilding = {
		Fire = function(Player: Player, Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BuildingTypeEnum"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].X)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Y)
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Position"].Z)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	PlayerRequestPalceBulidings = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["SnapToString"]: (string),
			["BuildingTypeEnum"]: (number),
			["Position"]: (Vector3),
		})) -> ()): () -> ()
			reliable_events[0] = Callback
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	PlayerDataUpdate = {
		Fire = function(Player: Player, Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_1 = 0
			local bool_1_pos_1 = alloc(1)
			if Value["Key"] == "Golds" then
				bool_1 = bit32.bor(bool_1, 0b0000000000000001)
			elseif Value["Key"] == "Elixirs" then
				bool_1 = bit32.bor(bool_1, 0b0000000000000010)
			elseif Value["Key"] == "Gems" then
				bool_1 = bit32.bor(bool_1, 0b0000000000000100)
			elseif Value["Key"] == "Level" then
				bool_1 = bit32.bor(bool_1, 0b0000000000001000)
			elseif Value["Key"] == "Experience" then
				bool_1 = bit32.bor(bool_1, 0b0000000000010000)
			else
				error("Invalid enumerator")
			end
			if Value["Value"] ~= nil then
				bool_1 = bit32.bor(bool_1, 0b0000000000100000)
				table.insert(outgoing_inst, Value["Value"])
			end
			buffer.writeu8(outgoing_buff, bool_1_pos_1, bool_1)
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_2 = 0
			local bool_2_pos_1 = alloc(1)
			if Value["Key"] == "Golds" then
				bool_2 = bit32.bor(bool_2, 0b0000000000000001)
			elseif Value["Key"] == "Elixirs" then
				bool_2 = bit32.bor(bool_2, 0b0000000000000010)
			elseif Value["Key"] == "Gems" then
				bool_2 = bit32.bor(bool_2, 0b0000000000000100)
			elseif Value["Key"] == "Level" then
				bool_2 = bit32.bor(bool_2, 0b0000000000001000)
			elseif Value["Key"] == "Experience" then
				bool_2 = bit32.bor(bool_2, 0b0000000000010000)
			else
				error("Invalid enumerator")
			end
			if Value["Value"] ~= nil then
				bool_2 = bit32.bor(bool_2, 0b0000000000100000)
				table.insert(outgoing_inst, Value["Value"])
			end
			buffer.writeu8(outgoing_buff, bool_2_pos_1, bool_2)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_3 = 0
			local bool_3_pos_1 = alloc(1)
			if Value["Key"] == "Golds" then
				bool_3 = bit32.bor(bool_3, 0b0000000000000001)
			elseif Value["Key"] == "Elixirs" then
				bool_3 = bit32.bor(bool_3, 0b0000000000000010)
			elseif Value["Key"] == "Gems" then
				bool_3 = bit32.bor(bool_3, 0b0000000000000100)
			elseif Value["Key"] == "Level" then
				bool_3 = bit32.bor(bool_3, 0b0000000000001000)
			elseif Value["Key"] == "Experience" then
				bool_3 = bit32.bor(bool_3, 0b0000000000010000)
			else
				error("Invalid enumerator")
			end
			if Value["Value"] ~= nil then
				bool_3 = bit32.bor(bool_3, 0b0000000000100000)
				table.insert(outgoing_inst, Value["Value"])
			end
			buffer.writeu8(outgoing_buff, bool_3_pos_1, bool_3)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_4 = 0
			local bool_4_pos_1 = alloc(1)
			if Value["Key"] == "Golds" then
				bool_4 = bit32.bor(bool_4, 0b0000000000000001)
			elseif Value["Key"] == "Elixirs" then
				bool_4 = bit32.bor(bool_4, 0b0000000000000010)
			elseif Value["Key"] == "Gems" then
				bool_4 = bit32.bor(bool_4, 0b0000000000000100)
			elseif Value["Key"] == "Level" then
				bool_4 = bit32.bor(bool_4, 0b0000000000001000)
			elseif Value["Key"] == "Experience" then
				bool_4 = bit32.bor(bool_4, 0b0000000000010000)
			else
				error("Invalid enumerator")
			end
			if Value["Value"] ~= nil then
				bool_4 = bit32.bor(bool_4, 0b0000000000100000)
				table.insert(outgoing_inst, Value["Value"])
			end
			buffer.writeu8(outgoing_buff, bool_4_pos_1, bool_4)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["Key"]: ("Golds" | "Elixirs" | "Gems" | "Level" | "Experience"),
			["Value"]: ((unknown)),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			local bool_5 = 0
			local bool_5_pos_1 = alloc(1)
			if Value["Key"] == "Golds" then
				bool_5 = bit32.bor(bool_5, 0b0000000000000001)
			elseif Value["Key"] == "Elixirs" then
				bool_5 = bit32.bor(bool_5, 0b0000000000000010)
			elseif Value["Key"] == "Gems" then
				bool_5 = bit32.bor(bool_5, 0b0000000000000100)
			elseif Value["Key"] == "Level" then
				bool_5 = bit32.bor(bool_5, 0b0000000000001000)
			elseif Value["Key"] == "Experience" then
				bool_5 = bit32.bor(bool_5, 0b0000000000010000)
			else
				error("Invalid enumerator")
			end
			if Value["Value"] ~= nil then
				bool_5 = bit32.bor(bool_5, 0b0000000000100000)
				table.insert(outgoing_inst, Value["Value"])
			end
			buffer.writeu8(outgoing_buff, bool_5_pos_1, bool_5)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	PlayerClickCollector = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["CollectorType"]: (string),
		})) -> ()): () -> ()
			reliable_events[2] = Callback
			return function()
				reliable_events[2] = nil
			end
		end,
	},
	LoadSnapshot = {
		Fire = function(Player: Player, Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Golds"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Elixirs"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Gems"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Level"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Experience"])
			local len_18 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_18)
			for i_6 = 1, len_18 do
				local val_6 = Value["Buildings"][i_6]
				local len_19 = #val_6["SnapToString"]
				assert(utf8.len(val_6["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_19)
				alloc(len_19)
				buffer.writestring(outgoing_buff, outgoing_apos, val_6["SnapToString"], len_19)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_6["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_6["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_6["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_6["LastCollectedTime"])
			end
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Capacity"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Capacity"])
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Golds"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Elixirs"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Gems"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Level"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Experience"])
			local len_20 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_20)
			for i_7 = 1, len_20 do
				local val_7 = Value["Buildings"][i_7]
				local len_21 = #val_7["SnapToString"]
				assert(utf8.len(val_7["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_21)
				alloc(len_21)
				buffer.writestring(outgoing_buff, outgoing_apos, val_7["SnapToString"], len_21)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_7["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_7["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_7["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_7["LastCollectedTime"])
			end
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Capacity"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Capacity"])
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Golds"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Elixirs"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Gems"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Level"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Experience"])
			local len_22 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_22)
			for i_8 = 1, len_22 do
				local val_8 = Value["Buildings"][i_8]
				local len_23 = #val_8["SnapToString"]
				assert(utf8.len(val_8["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
				alloc(len_23)
				buffer.writestring(outgoing_buff, outgoing_apos, val_8["SnapToString"], len_23)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_8["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_8["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_8["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_8["LastCollectedTime"])
			end
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Capacity"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Capacity"])
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Golds"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Elixirs"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Gems"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Level"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Experience"])
			local len_24 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_24)
			for i_9 = 1, len_24 do
				local val_9 = Value["Buildings"][i_9]
				local len_25 = #val_9["SnapToString"]
				assert(utf8.len(val_9["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_25)
				alloc(len_25)
				buffer.writestring(outgoing_buff, outgoing_apos, val_9["SnapToString"], len_25)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_9["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_9["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_9["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_9["LastCollectedTime"])
			end
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Capacity"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Capacity"])
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["Golds"]: (number),
			["Elixirs"]: (number),
			["Gems"]: (number),
			["Level"]: (number),
			["Experience"]: (number),
			["Buildings"]: ({ ({
				["SnapToString"]: (string),
				["BuildingTypeEnum"]: (number),
				["BuildingLevel"]: (number),
				["EndTime"]: (number),
				["LastCollectedTime"]: (number),
			}) }),
			["Collectors"]: ({
				["GoldCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
				["ElixirCollector"]: ({
					["Timestamp"]: (number),
					["ProductionRate"]: (number),
					["Capacity"]: (number),
				}),
			}),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Golds"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Elixirs"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Gems"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Level"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Experience"])
			local len_26 = #Value["Buildings"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_26)
			for i_10 = 1, len_26 do
				local val_10 = Value["Buildings"][i_10]
				local len_27 = #val_10["SnapToString"]
				assert(utf8.len(val_10["SnapToString"]) ~= nil, "value is not valid utf-8")
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_27)
				alloc(len_27)
				buffer.writestring(outgoing_buff, outgoing_apos, val_10["SnapToString"], len_27)
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_10["BuildingTypeEnum"])
				alloc(1)
				buffer.writeu8(outgoing_buff, outgoing_apos, val_10["BuildingLevel"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_10["EndTime"])
				alloc(4)
				buffer.writeu32(outgoing_buff, outgoing_apos, val_10["LastCollectedTime"])
			end
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["GoldCollector"]["Capacity"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Timestamp"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["ProductionRate"])
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value["Collectors"]["ElixirCollector"]["Capacity"])
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	ClientReady = {
		SetCallback = function(Callback: (Player: Player) -> ()): () -> ()
			reliable_events[1] = Callback
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	AssingZoneOwner = {
		Fire = function(Player: Player, Value: ({
			["FolderName"]: (string),
		}))
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local len_28 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_28)
			alloc(len_28)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_28)
			player_map[Player] = save()
		end,
		FireAll = function(Value: ({
			["FolderName"]: (string),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local len_29 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_29)
			alloc(len_29)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_29)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player, Value: ({
			["FolderName"]: (string),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local len_30 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_30)
			alloc(len_30)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_30)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player }, Value: ({
			["FolderName"]: (string),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local len_31 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_31)
			alloc(len_31)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_31)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any }, Value: ({
			["FolderName"]: (string),
		}))
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local len_32 = #Value["FolderName"]
			assert(utf8.len(Value["FolderName"]) ~= nil, "value is not valid utf-8")
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_32)
			alloc(len_32)
			buffer.writestring(outgoing_buff, outgoing_apos, Value["FolderName"], len_32)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
}
type Events = typeof(returns)
return returns
